"""Configuration and data models for the Polymarket A-S market making agent."""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional

from dotenv import load_dotenv

load_dotenv()


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class Side(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(str, Enum):
    LIMIT = "LIMIT"
    MARKET = "MARKET"


# ---------------------------------------------------------------------------
# Data models — existing (kept for compatibility)
# ---------------------------------------------------------------------------

@dataclass
class NewsSignal:
    source: str
    title: str
    summary: str
    url: str
    published_at: datetime
    relevance_score: float = 0.0
    sentiment_score: float = 0.0
    source_credibility: float = 0.5
    hours_ago: float = 0.0


@dataclass
class MarketInfo:
    condition_id: str
    question: str
    description: str
    tokens: list[dict]  # [{token_id, outcome, price}]
    volume: float = 0.0
    liquidity: float = 0.0
    end_date: Optional[str] = None
    active: bool = True


@dataclass
class OrderBookSnapshot:
    token_id: str
    bids: list[tuple[float, float]]  # (price, size)
    asks: list[tuple[float, float]]
    timestamp: datetime = field(default_factory=datetime.utcnow)

    @property
    def best_bid(self) -> float:
        return self.bids[0][0] if self.bids else 0.0

    @property
    def best_ask(self) -> float:
        return self.asks[0][0] if self.asks else 1.0

    @property
    def midpoint(self) -> float:
        return (self.best_bid + self.best_ask) / 2

    @property
    def spread(self) -> float:
        return self.best_ask - self.best_bid


@dataclass
class OrderBookAnalysis:
    spread: float
    midpoint: float
    best_bid: float
    best_ask: float
    bid_depth_total: float
    ask_depth_total: float
    imbalance_ratio: float
    slippage_estimates: dict[float, float]


@dataclass
class ExecutionResult:
    order_type: OrderType
    price: float
    size: float
    side: Side
    simulated: bool
    timestamp: datetime
    reasoning: list[str]
    slippage: float = 0.0


@dataclass
class PortfolioState:
    cash: float
    positions: dict[str, dict] = field(default_factory=dict)

    @property
    def total_value(self) -> float:
        position_value = sum(
            pos.get("qty", 0) * pos.get("current_price", pos.get("avg_price", 0))
            for pos in self.positions.values()
        )
        return self.cash + position_value


@dataclass
class BacktestResult:
    scenario_name: str
    trades: list[dict]
    portfolio_values: list[tuple[datetime, float]]
    final_pnl: float
    total_return_pct: float
    num_trades: int
    win_rate: float
    max_drawdown: float


# ---------------------------------------------------------------------------
# Data models — new (A-S market making)
# ---------------------------------------------------------------------------

@dataclass
class ArenaModel:
    """A model on the Chatbot Arena leaderboard."""
    model_name: str
    company: str
    elo_score: float
    elo_ci: float  # confidence interval (+/-)
    vote_count: int
    last_updated: datetime = field(default_factory=datetime.utcnow)


@dataclass
class Tweet:
    """A tweet/post from Twitter/Nitter."""
    author: str
    text: str
    created_at: datetime
    engagement: int = 0  # likes + retweets
    is_official_account: bool = False
    url: str = ""


@dataclass
class MultiOutcomeMarket:
    """A multi-outcome prediction market (e.g., 'best AI model end of month')."""
    event_id: str
    question: str
    outcomes: list[dict]  # [{name, token_id, price}]
    end_date: Optional[datetime] = None
    volume: float = 0.0
    liquidity: float = 0.0


@dataclass
class ASQuote:
    """A quote generated by the Avellaneda-Stoikov engine."""
    outcome: str
    token_id: str
    bid_price: float
    ask_price: float
    bid_size: float
    ask_size: float
    reservation_price: float
    spread: float
    fair_value: float
    inventory: float
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class InventoryState:
    """Current inventory across all outcomes."""
    positions: dict[str, float] = field(default_factory=dict)  # outcome -> quantity
    avg_prices: dict[str, float] = field(default_factory=dict)  # outcome -> avg entry price
    realized_pnl: float = 0.0
    unrealized_pnl: float = 0.0


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SOURCE_CREDIBILITY = {
    "reuters": 0.90,
    "ap": 0.90,
    "bbc": 0.85,
    "google_news": 0.60,
    "nitter": 0.70,
    "twitter": 0.70,
    "reddit": 0.40,
    "the_verge": 0.65,
    "techcrunch": 0.65,
    "ars_technica": 0.65,
    "generic": 0.50,
}

# Company -> model name prefixes for Arena leaderboard matching
COMPANY_MODEL_PREFIXES: dict[str, list[str]] = {
    "Anthropic": ["claude"],
    "OpenAI": ["gpt", "chatgpt", "o1", "o3", "o4"],
    "Google": ["gemini", "gemma"],
    "Meta": ["llama"],
    "xAI": ["grok"],
    "Mistral": ["mistral", "codestral"],
    "DeepSeek": ["deepseek"],
}

# Nitter instances for Twitter scraping (most are defunct as of 2025+)
NITTER_INSTANCES: list[str] = []  # Nitter is largely dead; we rely on AI news RSS

# Official AI company Twitter accounts
AI_TWITTER_ACCOUNTS = [
    "AnthropicAI",
    "OpenAI",
    "GoogleDeepMind",
    "GoogleAI",
    "MetaAI",
    "xaboratoryai",
    "MistralAI",
]

# AI news RSS feeds (primary signal source since Nitter is defunct)
AI_NEWS_RSS_FEEDS = {
    "the_verge_ai": "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    "techcrunch_ai": "https://techcrunch.com/category/artificial-intelligence/feed/",
    "ars_technica": "https://feeds.arstechnica.com/arstechnica/technology-lab",
    "mit_tech_review": "https://www.technologyreview.com/feed/",
    "venturebeat_ai": "https://venturebeat.com/category/ai/feed/",
    "google_ai_blog": "https://blog.google/technology/ai/rss/",
}

# Original RSS feeds (kept for general use)
RSS_FEEDS = {
    "bbc_world": "http://feeds.bbci.co.uk/news/world/rss.xml",
    "bbc_politics": "http://feeds.bbci.co.uk/news/politics/rss.xml",
    "bbc_business": "http://feeds.bbci.co.uk/news/business/rss.xml",
    "reuters_world": "https://www.reutersagency.com/feed/?taxonomy=best-sectors&post_type=best",
    "google_news": "https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en",
}

REDDIT_SUBREDDITS = ["polymarket", "politics", "worldnews", "economics", "news"]


# ---------------------------------------------------------------------------
# Settings
# ---------------------------------------------------------------------------

class Settings:
    """Central configuration loaded from environment variables."""

    def __init__(self):
        # Polymarket API
        self.clob_host: str = os.getenv("POLYMARKET_CLOB_HOST", "https://clob.polymarket.com")
        self.gamma_host: str = os.getenv("POLYMARKET_GAMMA_HOST", "https://gamma-api.polymarket.com")

        # Rust sidecar
        self.sidecar_host: str = os.getenv("SIDECAR_HOST", "http://localhost:8080")

        # Reddit (optional)
        self.reddit_client_id: str = os.getenv("REDDIT_CLIENT_ID", "")
        self.reddit_client_secret: str = os.getenv("REDDIT_CLIENT_SECRET", "")
        self.reddit_user_agent: str = os.getenv("REDDIT_USER_AGENT", "polymarket-agent/1.0")

        # Twitter (optional)
        self.twitter_bearer_token: str = os.getenv("TWITTER_BEARER_TOKEN", "")

        # Logging
        self.log_level: str = os.getenv("LOG_LEVEL", "INFO")

        # --- Avellaneda-Stoikov parameters ---
        self.as_gamma: float = float(os.getenv("AS_GAMMA", "0.1"))
        self.as_kappa: float = float(os.getenv("AS_KAPPA", "1.5"))
        self.as_base_order_size: float = float(os.getenv("AS_BASE_ORDER_SIZE", "10.0"))
        self.as_max_inventory: float = float(os.getenv("AS_MAX_INVENTORY", "100.0"))

        # --- Fair value parameters ---
        self.elo_tau_base: float = float(os.getenv("ELO_TAU_BASE", "150.0"))
        self.elo_sigma_daily: float = float(os.getenv("ELO_SIGMA_DAILY", "10.0"))
        self.signal_max_shift: float = float(os.getenv("SIGNAL_MAX_SHIFT", "0.15"))

        # --- Quote management ---
        self.quote_refresh_seconds: float = float(os.getenv("QUOTE_REFRESH_SECONDS", "30.0"))

        # --- Scoring (reused for signal adjustment) ---
        self.signal_alpha: float = float(os.getenv("SIGNAL_ALPHA", "2.0"))
        self.decay_half_life_hours: float = float(os.getenv("DECAY_HALF_LIFE_HOURS", "4.0"))
        self.min_relevance_threshold: float = float(os.getenv("MIN_RELEVANCE_THRESHOLD", "0.15"))

        # --- Risk parameters ---
        self.max_position_pct: float = float(os.getenv("MAX_POSITION_PCT", "0.05"))
        self.max_portfolio_exposure: float = float(os.getenv("MAX_PORTFOLIO_EXPOSURE", "0.30"))
        self.stop_loss_pct: float = float(os.getenv("STOP_LOSS_PCT", "0.15"))

        # --- Volatility ---
        self.min_sigma: float = float(os.getenv("MIN_SIGMA", "0.01"))
        self.max_sigma: float = float(os.getenv("MAX_SIGMA", "0.20"))

        # --- Data sources ---
        self.source_credibility: dict[str, float] = SOURCE_CREDIBILITY
        self.company_model_prefixes: dict[str, list[str]] = COMPANY_MODEL_PREFIXES
        self.nitter_instances: list[str] = NITTER_INSTANCES
        self.ai_twitter_accounts: list[str] = AI_TWITTER_ACCOUNTS
        self.ai_news_rss_feeds: dict[str, str] = AI_NEWS_RSS_FEEDS
        self.news_max_age_hours: int = int(os.getenv("NEWS_MAX_AGE_HOURS", "24"))
        self.polling_interval_seconds: int = int(os.getenv("POLLING_INTERVAL_SECONDS", "30"))

        # --- Backtest ---
        self.starting_bankroll: float = float(os.getenv("STARTING_BANKROLL", "10000.0"))
        self.fee_rate_bps: float = float(os.getenv("FEE_RATE_BPS", "0.0"))
